<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        Country::upsert(
            $this->countries(),
            ['iso_alpha2'],
            ['en_name', 'es_name', 'iso_alpha3', 'phone_code', 'sort_order'],
        );
    }

    /**
     * @return list<array{en_name: string, es_name: string, iso_alpha2: string, iso_alpha3: string, phone_code: string, sort_order: int}>
     */
    private function countries(): array
    {
        return [
            // ── Colombia (sort_order = 0) ───────────────────────────
            ['en_name' => 'Colombia', 'es_name' => 'Colombia', 'iso_alpha2' => 'CO', 'iso_alpha3' => 'COL', 'phone_code' => '+57', 'sort_order' => 0],

            // ── LATAM countries (sort_order 1–20) ───────────────────
            ['en_name' => 'Mexico', 'es_name' => 'México', 'iso_alpha2' => 'MX', 'iso_alpha3' => 'MEX', 'phone_code' => '+52', 'sort_order' => 1],
            ['en_name' => 'Argentina', 'es_name' => 'Argentina', 'iso_alpha2' => 'AR', 'iso_alpha3' => 'ARG', 'phone_code' => '+54', 'sort_order' => 2],
            ['en_name' => 'Brazil', 'es_name' => 'Brasil', 'iso_alpha2' => 'BR', 'iso_alpha3' => 'BRA', 'phone_code' => '+55', 'sort_order' => 3],
            ['en_name' => 'Chile', 'es_name' => 'Chile', 'iso_alpha2' => 'CL', 'iso_alpha3' => 'CHL', 'phone_code' => '+56', 'sort_order' => 4],
            ['en_name' => 'Peru', 'es_name' => 'Perú', 'iso_alpha2' => 'PE', 'iso_alpha3' => 'PER', 'phone_code' => '+51', 'sort_order' => 5],
            ['en_name' => 'Ecuador', 'es_name' => 'Ecuador', 'iso_alpha2' => 'EC', 'iso_alpha3' => 'ECU', 'phone_code' => '+593', 'sort_order' => 6],
            ['en_name' => 'Venezuela', 'es_name' => 'Venezuela', 'iso_alpha2' => 'VE', 'iso_alpha3' => 'VEN', 'phone_code' => '+58', 'sort_order' => 7],
            ['en_name' => 'Bolivia', 'es_name' => 'Bolivia', 'iso_alpha2' => 'BO', 'iso_alpha3' => 'BOL', 'phone_code' => '+591', 'sort_order' => 8],
            ['en_name' => 'Paraguay', 'es_name' => 'Paraguay', 'iso_alpha2' => 'PY', 'iso_alpha3' => 'PRY', 'phone_code' => '+595', 'sort_order' => 9],
            ['en_name' => 'Uruguay', 'es_name' => 'Uruguay', 'iso_alpha2' => 'UY', 'iso_alpha3' => 'URY', 'phone_code' => '+598', 'sort_order' => 10],
            ['en_name' => 'Panama', 'es_name' => 'Panamá', 'iso_alpha2' => 'PA', 'iso_alpha3' => 'PAN', 'phone_code' => '+507', 'sort_order' => 11],
            ['en_name' => 'Costa Rica', 'es_name' => 'Costa Rica', 'iso_alpha2' => 'CR', 'iso_alpha3' => 'CRI', 'phone_code' => '+506', 'sort_order' => 12],
            ['en_name' => 'Guatemala', 'es_name' => 'Guatemala', 'iso_alpha2' => 'GT', 'iso_alpha3' => 'GTM', 'phone_code' => '+502', 'sort_order' => 13],
            ['en_name' => 'Honduras', 'es_name' => 'Honduras', 'iso_alpha2' => 'HN', 'iso_alpha3' => 'HND', 'phone_code' => '+504', 'sort_order' => 14],
            ['en_name' => 'El Salvador', 'es_name' => 'El Salvador', 'iso_alpha2' => 'SV', 'iso_alpha3' => 'SLV', 'phone_code' => '+503', 'sort_order' => 15],
            ['en_name' => 'Nicaragua', 'es_name' => 'Nicaragua', 'iso_alpha2' => 'NI', 'iso_alpha3' => 'NIC', 'phone_code' => '+505', 'sort_order' => 16],
            ['en_name' => 'Cuba', 'es_name' => 'Cuba', 'iso_alpha2' => 'CU', 'iso_alpha3' => 'CUB', 'phone_code' => '+53', 'sort_order' => 17],
            ['en_name' => 'Dominican Republic', 'es_name' => 'República Dominicana', 'iso_alpha2' => 'DO', 'iso_alpha3' => 'DOM', 'phone_code' => '+1-809', 'sort_order' => 18],
            ['en_name' => 'Puerto Rico', 'es_name' => 'Puerto Rico', 'iso_alpha2' => 'PR', 'iso_alpha3' => 'PRI', 'phone_code' => '+1-787', 'sort_order' => 19],
            ['en_name' => 'Haiti', 'es_name' => 'Haití', 'iso_alpha2' => 'HT', 'iso_alpha3' => 'HTI', 'phone_code' => '+509', 'sort_order' => 20],

            // ── Rest of the world (sort_order 100+) ─────────────────

            // North America
            ['en_name' => 'United States', 'es_name' => 'Estados Unidos', 'iso_alpha2' => 'US', 'iso_alpha3' => 'USA', 'phone_code' => '+1', 'sort_order' => 100],
            ['en_name' => 'Canada', 'es_name' => 'Canadá', 'iso_alpha2' => 'CA', 'iso_alpha3' => 'CAN', 'phone_code' => '+1', 'sort_order' => 101],

            // Europe
            ['en_name' => 'Spain', 'es_name' => 'España', 'iso_alpha2' => 'ES', 'iso_alpha3' => 'ESP', 'phone_code' => '+34', 'sort_order' => 102],
            ['en_name' => 'United Kingdom', 'es_name' => 'Reino Unido', 'iso_alpha2' => 'GB', 'iso_alpha3' => 'GBR', 'phone_code' => '+44', 'sort_order' => 103],
            ['en_name' => 'France', 'es_name' => 'Francia', 'iso_alpha2' => 'FR', 'iso_alpha3' => 'FRA', 'phone_code' => '+33', 'sort_order' => 104],
            ['en_name' => 'Germany', 'es_name' => 'Alemania', 'iso_alpha2' => 'DE', 'iso_alpha3' => 'DEU', 'phone_code' => '+49', 'sort_order' => 105],
            ['en_name' => 'Italy', 'es_name' => 'Italia', 'iso_alpha2' => 'IT', 'iso_alpha3' => 'ITA', 'phone_code' => '+39', 'sort_order' => 106],
            ['en_name' => 'Portugal', 'es_name' => 'Portugal', 'iso_alpha2' => 'PT', 'iso_alpha3' => 'PRT', 'phone_code' => '+351', 'sort_order' => 107],
            ['en_name' => 'Netherlands', 'es_name' => 'Países Bajos', 'iso_alpha2' => 'NL', 'iso_alpha3' => 'NLD', 'phone_code' => '+31', 'sort_order' => 108],
            ['en_name' => 'Belgium', 'es_name' => 'Bélgica', 'iso_alpha2' => 'BE', 'iso_alpha3' => 'BEL', 'phone_code' => '+32', 'sort_order' => 109],
            ['en_name' => 'Switzerland', 'es_name' => 'Suiza', 'iso_alpha2' => 'CH', 'iso_alpha3' => 'CHE', 'phone_code' => '+41', 'sort_order' => 110],
            ['en_name' => 'Austria', 'es_name' => 'Austria', 'iso_alpha2' => 'AT', 'iso_alpha3' => 'AUT', 'phone_code' => '+43', 'sort_order' => 111],
            ['en_name' => 'Sweden', 'es_name' => 'Suecia', 'iso_alpha2' => 'SE', 'iso_alpha3' => 'SWE', 'phone_code' => '+46', 'sort_order' => 112],
            ['en_name' => 'Norway', 'es_name' => 'Noruega', 'iso_alpha2' => 'NO', 'iso_alpha3' => 'NOR', 'phone_code' => '+47', 'sort_order' => 113],
            ['en_name' => 'Denmark', 'es_name' => 'Dinamarca', 'iso_alpha2' => 'DK', 'iso_alpha3' => 'DNK', 'phone_code' => '+45', 'sort_order' => 114],
            ['en_name' => 'Finland', 'es_name' => 'Finlandia', 'iso_alpha2' => 'FI', 'iso_alpha3' => 'FIN', 'phone_code' => '+358', 'sort_order' => 115],
            ['en_name' => 'Ireland', 'es_name' => 'Irlanda', 'iso_alpha2' => 'IE', 'iso_alpha3' => 'IRL', 'phone_code' => '+353', 'sort_order' => 116],
            ['en_name' => 'Poland', 'es_name' => 'Polonia', 'iso_alpha2' => 'PL', 'iso_alpha3' => 'POL', 'phone_code' => '+48', 'sort_order' => 117],
            ['en_name' => 'Czech Republic', 'es_name' => 'República Checa', 'iso_alpha2' => 'CZ', 'iso_alpha3' => 'CZE', 'phone_code' => '+420', 'sort_order' => 118],
            ['en_name' => 'Romania', 'es_name' => 'Rumania', 'iso_alpha2' => 'RO', 'iso_alpha3' => 'ROU', 'phone_code' => '+40', 'sort_order' => 119],
            ['en_name' => 'Hungary', 'es_name' => 'Hungría', 'iso_alpha2' => 'HU', 'iso_alpha3' => 'HUN', 'phone_code' => '+36', 'sort_order' => 120],
            ['en_name' => 'Greece', 'es_name' => 'Grecia', 'iso_alpha2' => 'GR', 'iso_alpha3' => 'GRC', 'phone_code' => '+30', 'sort_order' => 121],
            ['en_name' => 'Bulgaria', 'es_name' => 'Bulgaria', 'iso_alpha2' => 'BG', 'iso_alpha3' => 'BGR', 'phone_code' => '+359', 'sort_order' => 122],
            ['en_name' => 'Croatia', 'es_name' => 'Croacia', 'iso_alpha2' => 'HR', 'iso_alpha3' => 'HRV', 'phone_code' => '+385', 'sort_order' => 123],
            ['en_name' => 'Slovakia', 'es_name' => 'Eslovaquia', 'iso_alpha2' => 'SK', 'iso_alpha3' => 'SVK', 'phone_code' => '+421', 'sort_order' => 124],
            ['en_name' => 'Slovenia', 'es_name' => 'Eslovenia', 'iso_alpha2' => 'SI', 'iso_alpha3' => 'SVN', 'phone_code' => '+386', 'sort_order' => 125],
            ['en_name' => 'Lithuania', 'es_name' => 'Lituania', 'iso_alpha2' => 'LT', 'iso_alpha3' => 'LTU', 'phone_code' => '+370', 'sort_order' => 126],
            ['en_name' => 'Latvia', 'es_name' => 'Letonia', 'iso_alpha2' => 'LV', 'iso_alpha3' => 'LVA', 'phone_code' => '+371', 'sort_order' => 127],
            ['en_name' => 'Estonia', 'es_name' => 'Estonia', 'iso_alpha2' => 'EE', 'iso_alpha3' => 'EST', 'phone_code' => '+372', 'sort_order' => 128],
            ['en_name' => 'Luxembourg', 'es_name' => 'Luxemburgo', 'iso_alpha2' => 'LU', 'iso_alpha3' => 'LUX', 'phone_code' => '+352', 'sort_order' => 129],
            ['en_name' => 'Malta', 'es_name' => 'Malta', 'iso_alpha2' => 'MT', 'iso_alpha3' => 'MLT', 'phone_code' => '+356', 'sort_order' => 130],
            ['en_name' => 'Cyprus', 'es_name' => 'Chipre', 'iso_alpha2' => 'CY', 'iso_alpha3' => 'CYP', 'phone_code' => '+357', 'sort_order' => 131],
            ['en_name' => 'Iceland', 'es_name' => 'Islandia', 'iso_alpha2' => 'IS', 'iso_alpha3' => 'ISL', 'phone_code' => '+354', 'sort_order' => 132],
            ['en_name' => 'Albania', 'es_name' => 'Albania', 'iso_alpha2' => 'AL', 'iso_alpha3' => 'ALB', 'phone_code' => '+355', 'sort_order' => 133],
            ['en_name' => 'North Macedonia', 'es_name' => 'Macedonia del Norte', 'iso_alpha2' => 'MK', 'iso_alpha3' => 'MKD', 'phone_code' => '+389', 'sort_order' => 134],
            ['en_name' => 'Montenegro', 'es_name' => 'Montenegro', 'iso_alpha2' => 'ME', 'iso_alpha3' => 'MNE', 'phone_code' => '+382', 'sort_order' => 135],
            ['en_name' => 'Serbia', 'es_name' => 'Serbia', 'iso_alpha2' => 'RS', 'iso_alpha3' => 'SRB', 'phone_code' => '+381', 'sort_order' => 136],
            ['en_name' => 'Bosnia and Herzegovina', 'es_name' => 'Bosnia y Herzegovina', 'iso_alpha2' => 'BA', 'iso_alpha3' => 'BIH', 'phone_code' => '+387', 'sort_order' => 137],
            ['en_name' => 'Moldova', 'es_name' => 'Moldavia', 'iso_alpha2' => 'MD', 'iso_alpha3' => 'MDA', 'phone_code' => '+373', 'sort_order' => 138],
            ['en_name' => 'Ukraine', 'es_name' => 'Ucrania', 'iso_alpha2' => 'UA', 'iso_alpha3' => 'UKR', 'phone_code' => '+380', 'sort_order' => 139],
            ['en_name' => 'Belarus', 'es_name' => 'Bielorrusia', 'iso_alpha2' => 'BY', 'iso_alpha3' => 'BLR', 'phone_code' => '+375', 'sort_order' => 140],
            ['en_name' => 'Russia', 'es_name' => 'Rusia', 'iso_alpha2' => 'RU', 'iso_alpha3' => 'RUS', 'phone_code' => '+7', 'sort_order' => 141],
            ['en_name' => 'Georgia', 'es_name' => 'Georgia', 'iso_alpha2' => 'GE', 'iso_alpha3' => 'GEO', 'phone_code' => '+995', 'sort_order' => 142],
            ['en_name' => 'Armenia', 'es_name' => 'Armenia', 'iso_alpha2' => 'AM', 'iso_alpha3' => 'ARM', 'phone_code' => '+374', 'sort_order' => 143],
            ['en_name' => 'Azerbaijan', 'es_name' => 'Azerbaiyán', 'iso_alpha2' => 'AZ', 'iso_alpha3' => 'AZE', 'phone_code' => '+994', 'sort_order' => 144],
            ['en_name' => 'Andorra', 'es_name' => 'Andorra', 'iso_alpha2' => 'AD', 'iso_alpha3' => 'AND', 'phone_code' => '+376', 'sort_order' => 145],
            ['en_name' => 'Monaco', 'es_name' => 'Mónaco', 'iso_alpha2' => 'MC', 'iso_alpha3' => 'MCO', 'phone_code' => '+377', 'sort_order' => 146],
            ['en_name' => 'San Marino', 'es_name' => 'San Marino', 'iso_alpha2' => 'SM', 'iso_alpha3' => 'SMR', 'phone_code' => '+378', 'sort_order' => 147],
            ['en_name' => 'Vatican City', 'es_name' => 'Ciudad del Vaticano', 'iso_alpha2' => 'VA', 'iso_alpha3' => 'VAT', 'phone_code' => '+379', 'sort_order' => 148],
            ['en_name' => 'Liechtenstein', 'es_name' => 'Liechtenstein', 'iso_alpha2' => 'LI', 'iso_alpha3' => 'LIE', 'phone_code' => '+423', 'sort_order' => 149],
            ['en_name' => 'Kosovo', 'es_name' => 'Kosovo', 'iso_alpha2' => 'XK', 'iso_alpha3' => 'XKX', 'phone_code' => '+383', 'sort_order' => 150],
            ['en_name' => 'Turkey', 'es_name' => 'Turquía', 'iso_alpha2' => 'TR', 'iso_alpha3' => 'TUR', 'phone_code' => '+90', 'sort_order' => 151],

            // Caribbean
            ['en_name' => 'Jamaica', 'es_name' => 'Jamaica', 'iso_alpha2' => 'JM', 'iso_alpha3' => 'JAM', 'phone_code' => '+1-876', 'sort_order' => 152],
            ['en_name' => 'Trinidad and Tobago', 'es_name' => 'Trinidad y Tobago', 'iso_alpha2' => 'TT', 'iso_alpha3' => 'TTO', 'phone_code' => '+1-868', 'sort_order' => 153],
            ['en_name' => 'Barbados', 'es_name' => 'Barbados', 'iso_alpha2' => 'BB', 'iso_alpha3' => 'BRB', 'phone_code' => '+1-246', 'sort_order' => 154],
            ['en_name' => 'Bahamas', 'es_name' => 'Bahamas', 'iso_alpha2' => 'BS', 'iso_alpha3' => 'BHS', 'phone_code' => '+1-242', 'sort_order' => 155],
            ['en_name' => 'Saint Lucia', 'es_name' => 'Santa Lucía', 'iso_alpha2' => 'LC', 'iso_alpha3' => 'LCA', 'phone_code' => '+1-758', 'sort_order' => 156],
            ['en_name' => 'Grenada', 'es_name' => 'Granada', 'iso_alpha2' => 'GD', 'iso_alpha3' => 'GRD', 'phone_code' => '+1-473', 'sort_order' => 157],
            ['en_name' => 'Saint Vincent and the Grenadines', 'es_name' => 'San Vicente y las Granadinas', 'iso_alpha2' => 'VC', 'iso_alpha3' => 'VCT', 'phone_code' => '+1-784', 'sort_order' => 158],
            ['en_name' => 'Antigua and Barbuda', 'es_name' => 'Antigua y Barbuda', 'iso_alpha2' => 'AG', 'iso_alpha3' => 'ATG', 'phone_code' => '+1-268', 'sort_order' => 159],
            ['en_name' => 'Dominica', 'es_name' => 'Dominica', 'iso_alpha2' => 'DM', 'iso_alpha3' => 'DMA', 'phone_code' => '+1-767', 'sort_order' => 160],
            ['en_name' => 'Saint Kitts and Nevis', 'es_name' => 'San Cristóbal y Nieves', 'iso_alpha2' => 'KN', 'iso_alpha3' => 'KNA', 'phone_code' => '+1-869', 'sort_order' => 161],
            ['en_name' => 'Belize', 'es_name' => 'Belice', 'iso_alpha2' => 'BZ', 'iso_alpha3' => 'BLZ', 'phone_code' => '+501', 'sort_order' => 162],
            ['en_name' => 'Guyana', 'es_name' => 'Guyana', 'iso_alpha2' => 'GY', 'iso_alpha3' => 'GUY', 'phone_code' => '+592', 'sort_order' => 163],
            ['en_name' => 'Suriname', 'es_name' => 'Surinam', 'iso_alpha2' => 'SR', 'iso_alpha3' => 'SUR', 'phone_code' => '+597', 'sort_order' => 164],

            // Asia
            ['en_name' => 'China', 'es_name' => 'China', 'iso_alpha2' => 'CN', 'iso_alpha3' => 'CHN', 'phone_code' => '+86', 'sort_order' => 200],
            ['en_name' => 'Japan', 'es_name' => 'Japón', 'iso_alpha2' => 'JP', 'iso_alpha3' => 'JPN', 'phone_code' => '+81', 'sort_order' => 201],
            ['en_name' => 'South Korea', 'es_name' => 'Corea del Sur', 'iso_alpha2' => 'KR', 'iso_alpha3' => 'KOR', 'phone_code' => '+82', 'sort_order' => 202],
            ['en_name' => 'North Korea', 'es_name' => 'Corea del Norte', 'iso_alpha2' => 'KP', 'iso_alpha3' => 'PRK', 'phone_code' => '+850', 'sort_order' => 203],
            ['en_name' => 'India', 'es_name' => 'India', 'iso_alpha2' => 'IN', 'iso_alpha3' => 'IND', 'phone_code' => '+91', 'sort_order' => 204],
            ['en_name' => 'Indonesia', 'es_name' => 'Indonesia', 'iso_alpha2' => 'ID', 'iso_alpha3' => 'IDN', 'phone_code' => '+62', 'sort_order' => 205],
            ['en_name' => 'Pakistan', 'es_name' => 'Pakistán', 'iso_alpha2' => 'PK', 'iso_alpha3' => 'PAK', 'phone_code' => '+92', 'sort_order' => 206],
            ['en_name' => 'Bangladesh', 'es_name' => 'Bangladesh', 'iso_alpha2' => 'BD', 'iso_alpha3' => 'BGD', 'phone_code' => '+880', 'sort_order' => 207],
            ['en_name' => 'Philippines', 'es_name' => 'Filipinas', 'iso_alpha2' => 'PH', 'iso_alpha3' => 'PHL', 'phone_code' => '+63', 'sort_order' => 208],
            ['en_name' => 'Vietnam', 'es_name' => 'Vietnam', 'iso_alpha2' => 'VN', 'iso_alpha3' => 'VNM', 'phone_code' => '+84', 'sort_order' => 209],
            ['en_name' => 'Thailand', 'es_name' => 'Tailandia', 'iso_alpha2' => 'TH', 'iso_alpha3' => 'THA', 'phone_code' => '+66', 'sort_order' => 210],
            ['en_name' => 'Myanmar', 'es_name' => 'Myanmar', 'iso_alpha2' => 'MM', 'iso_alpha3' => 'MMR', 'phone_code' => '+95', 'sort_order' => 211],
            ['en_name' => 'Malaysia', 'es_name' => 'Malasia', 'iso_alpha2' => 'MY', 'iso_alpha3' => 'MYS', 'phone_code' => '+60', 'sort_order' => 212],
            ['en_name' => 'Singapore', 'es_name' => 'Singapur', 'iso_alpha2' => 'SG', 'iso_alpha3' => 'SGP', 'phone_code' => '+65', 'sort_order' => 213],
            ['en_name' => 'Cambodia', 'es_name' => 'Camboya', 'iso_alpha2' => 'KH', 'iso_alpha3' => 'KHM', 'phone_code' => '+855', 'sort_order' => 214],
            ['en_name' => 'Laos', 'es_name' => 'Laos', 'iso_alpha2' => 'LA', 'iso_alpha3' => 'LAO', 'phone_code' => '+856', 'sort_order' => 215],
            ['en_name' => 'Mongolia', 'es_name' => 'Mongolia', 'iso_alpha2' => 'MN', 'iso_alpha3' => 'MNG', 'phone_code' => '+976', 'sort_order' => 216],
            ['en_name' => 'Nepal', 'es_name' => 'Nepal', 'iso_alpha2' => 'NP', 'iso_alpha3' => 'NPL', 'phone_code' => '+977', 'sort_order' => 217],
            ['en_name' => 'Sri Lanka', 'es_name' => 'Sri Lanka', 'iso_alpha2' => 'LK', 'iso_alpha3' => 'LKA', 'phone_code' => '+94', 'sort_order' => 218],
            ['en_name' => 'Maldives', 'es_name' => 'Maldivas', 'iso_alpha2' => 'MV', 'iso_alpha3' => 'MDV', 'phone_code' => '+960', 'sort_order' => 219],
            ['en_name' => 'Bhutan', 'es_name' => 'Bután', 'iso_alpha2' => 'BT', 'iso_alpha3' => 'BTN', 'phone_code' => '+975', 'sort_order' => 220],
            ['en_name' => 'Brunei', 'es_name' => 'Brunei', 'iso_alpha2' => 'BN', 'iso_alpha3' => 'BRN', 'phone_code' => '+673', 'sort_order' => 221],
            ['en_name' => 'Timor-Leste', 'es_name' => 'Timor Oriental', 'iso_alpha2' => 'TL', 'iso_alpha3' => 'TLS', 'phone_code' => '+670', 'sort_order' => 222],
            ['en_name' => 'Taiwan', 'es_name' => 'Taiwán', 'iso_alpha2' => 'TW', 'iso_alpha3' => 'TWN', 'phone_code' => '+886', 'sort_order' => 223],
            ['en_name' => 'Hong Kong', 'es_name' => 'Hong Kong', 'iso_alpha2' => 'HK', 'iso_alpha3' => 'HKG', 'phone_code' => '+852', 'sort_order' => 224],
            ['en_name' => 'Macau', 'es_name' => 'Macao', 'iso_alpha2' => 'MO', 'iso_alpha3' => 'MAC', 'phone_code' => '+853', 'sort_order' => 225],

            // Central Asia
            ['en_name' => 'Kazakhstan', 'es_name' => 'Kazajistán', 'iso_alpha2' => 'KZ', 'iso_alpha3' => 'KAZ', 'phone_code' => '+7', 'sort_order' => 226],
            ['en_name' => 'Uzbekistan', 'es_name' => 'Uzbekistán', 'iso_alpha2' => 'UZ', 'iso_alpha3' => 'UZB', 'phone_code' => '+998', 'sort_order' => 227],
            ['en_name' => 'Turkmenistan', 'es_name' => 'Turkmenistán', 'iso_alpha2' => 'TM', 'iso_alpha3' => 'TKM', 'phone_code' => '+993', 'sort_order' => 228],
            ['en_name' => 'Kyrgyzstan', 'es_name' => 'Kirguistán', 'iso_alpha2' => 'KG', 'iso_alpha3' => 'KGZ', 'phone_code' => '+996', 'sort_order' => 229],
            ['en_name' => 'Tajikistan', 'es_name' => 'Tayikistán', 'iso_alpha2' => 'TJ', 'iso_alpha3' => 'TJK', 'phone_code' => '+992', 'sort_order' => 230],
            ['en_name' => 'Afghanistan', 'es_name' => 'Afganistán', 'iso_alpha2' => 'AF', 'iso_alpha3' => 'AFG', 'phone_code' => '+93', 'sort_order' => 231],

            // Middle East
            ['en_name' => 'Saudi Arabia', 'es_name' => 'Arabia Saudita', 'iso_alpha2' => 'SA', 'iso_alpha3' => 'SAU', 'phone_code' => '+966', 'sort_order' => 250],
            ['en_name' => 'United Arab Emirates', 'es_name' => 'Emiratos Árabes Unidos', 'iso_alpha2' => 'AE', 'iso_alpha3' => 'ARE', 'phone_code' => '+971', 'sort_order' => 251],
            ['en_name' => 'Israel', 'es_name' => 'Israel', 'iso_alpha2' => 'IL', 'iso_alpha3' => 'ISR', 'phone_code' => '+972', 'sort_order' => 252],
            ['en_name' => 'Iran', 'es_name' => 'Irán', 'iso_alpha2' => 'IR', 'iso_alpha3' => 'IRN', 'phone_code' => '+98', 'sort_order' => 253],
            ['en_name' => 'Iraq', 'es_name' => 'Irak', 'iso_alpha2' => 'IQ', 'iso_alpha3' => 'IRQ', 'phone_code' => '+964', 'sort_order' => 254],
            ['en_name' => 'Kuwait', 'es_name' => 'Kuwait', 'iso_alpha2' => 'KW', 'iso_alpha3' => 'KWT', 'phone_code' => '+965', 'sort_order' => 255],
            ['en_name' => 'Qatar', 'es_name' => 'Catar', 'iso_alpha2' => 'QA', 'iso_alpha3' => 'QAT', 'phone_code' => '+974', 'sort_order' => 256],
            ['en_name' => 'Bahrain', 'es_name' => 'Barein', 'iso_alpha2' => 'BH', 'iso_alpha3' => 'BHR', 'phone_code' => '+973', 'sort_order' => 257],
            ['en_name' => 'Oman', 'es_name' => 'Omán', 'iso_alpha2' => 'OM', 'iso_alpha3' => 'OMN', 'phone_code' => '+968', 'sort_order' => 258],
            ['en_name' => 'Yemen', 'es_name' => 'Yemen', 'iso_alpha2' => 'YE', 'iso_alpha3' => 'YEM', 'phone_code' => '+967', 'sort_order' => 259],
            ['en_name' => 'Jordan', 'es_name' => 'Jordania', 'iso_alpha2' => 'JO', 'iso_alpha3' => 'JOR', 'phone_code' => '+962', 'sort_order' => 260],
            ['en_name' => 'Lebanon', 'es_name' => 'Líbano', 'iso_alpha2' => 'LB', 'iso_alpha3' => 'LBN', 'phone_code' => '+961', 'sort_order' => 261],
            ['en_name' => 'Syria', 'es_name' => 'Siria', 'iso_alpha2' => 'SY', 'iso_alpha3' => 'SYR', 'phone_code' => '+963', 'sort_order' => 262],
            ['en_name' => 'Palestine', 'es_name' => 'Palestina', 'iso_alpha2' => 'PS', 'iso_alpha3' => 'PSE', 'phone_code' => '+970', 'sort_order' => 263],

            // Africa
            ['en_name' => 'Nigeria', 'es_name' => 'Nigeria', 'iso_alpha2' => 'NG', 'iso_alpha3' => 'NGA', 'phone_code' => '+234', 'sort_order' => 300],
            ['en_name' => 'South Africa', 'es_name' => 'Sudáfrica', 'iso_alpha2' => 'ZA', 'iso_alpha3' => 'ZAF', 'phone_code' => '+27', 'sort_order' => 301],
            ['en_name' => 'Egypt', 'es_name' => 'Egipto', 'iso_alpha2' => 'EG', 'iso_alpha3' => 'EGY', 'phone_code' => '+20', 'sort_order' => 302],
            ['en_name' => 'Kenya', 'es_name' => 'Kenia', 'iso_alpha2' => 'KE', 'iso_alpha3' => 'KEN', 'phone_code' => '+254', 'sort_order' => 303],
            ['en_name' => 'Ethiopia', 'es_name' => 'Etiopía', 'iso_alpha2' => 'ET', 'iso_alpha3' => 'ETH', 'phone_code' => '+251', 'sort_order' => 304],
            ['en_name' => 'Ghana', 'es_name' => 'Ghana', 'iso_alpha2' => 'GH', 'iso_alpha3' => 'GHA', 'phone_code' => '+233', 'sort_order' => 305],
            ['en_name' => 'Tanzania', 'es_name' => 'Tanzania', 'iso_alpha2' => 'TZ', 'iso_alpha3' => 'TZA', 'phone_code' => '+255', 'sort_order' => 306],
            ['en_name' => 'Morocco', 'es_name' => 'Marruecos', 'iso_alpha2' => 'MA', 'iso_alpha3' => 'MAR', 'phone_code' => '+212', 'sort_order' => 307],
            ['en_name' => 'Algeria', 'es_name' => 'Argelia', 'iso_alpha2' => 'DZ', 'iso_alpha3' => 'DZA', 'phone_code' => '+213', 'sort_order' => 308],
            ['en_name' => 'Tunisia', 'es_name' => 'Túnez', 'iso_alpha2' => 'TN', 'iso_alpha3' => 'TUN', 'phone_code' => '+216', 'sort_order' => 309],
            ['en_name' => 'Libya', 'es_name' => 'Libia', 'iso_alpha2' => 'LY', 'iso_alpha3' => 'LBY', 'phone_code' => '+218', 'sort_order' => 310],
            ['en_name' => 'Uganda', 'es_name' => 'Uganda', 'iso_alpha2' => 'UG', 'iso_alpha3' => 'UGA', 'phone_code' => '+256', 'sort_order' => 311],
            ['en_name' => 'Cameroon', 'es_name' => 'Camerún', 'iso_alpha2' => 'CM', 'iso_alpha3' => 'CMR', 'phone_code' => '+237', 'sort_order' => 312],
            ['en_name' => 'Senegal', 'es_name' => 'Senegal', 'iso_alpha2' => 'SN', 'iso_alpha3' => 'SEN', 'phone_code' => '+221', 'sort_order' => 313],
            ['en_name' => 'Ivory Coast', 'es_name' => 'Costa de Marfil', 'iso_alpha2' => 'CI', 'iso_alpha3' => 'CIV', 'phone_code' => '+225', 'sort_order' => 314],
            ['en_name' => 'Democratic Republic of the Congo', 'es_name' => 'República Democrática del Congo', 'iso_alpha2' => 'CD', 'iso_alpha3' => 'COD', 'phone_code' => '+243', 'sort_order' => 315],
            ['en_name' => 'Republic of the Congo', 'es_name' => 'República del Congo', 'iso_alpha2' => 'CG', 'iso_alpha3' => 'COG', 'phone_code' => '+242', 'sort_order' => 316],
            ['en_name' => 'Angola', 'es_name' => 'Angola', 'iso_alpha2' => 'AO', 'iso_alpha3' => 'AGO', 'phone_code' => '+244', 'sort_order' => 317],
            ['en_name' => 'Mozambique', 'es_name' => 'Mozambique', 'iso_alpha2' => 'MZ', 'iso_alpha3' => 'MOZ', 'phone_code' => '+258', 'sort_order' => 318],
            ['en_name' => 'Madagascar', 'es_name' => 'Madagascar', 'iso_alpha2' => 'MG', 'iso_alpha3' => 'MDG', 'phone_code' => '+261', 'sort_order' => 319],
            ['en_name' => 'Zambia', 'es_name' => 'Zambia', 'iso_alpha2' => 'ZM', 'iso_alpha3' => 'ZMB', 'phone_code' => '+260', 'sort_order' => 320],
            ['en_name' => 'Zimbabwe', 'es_name' => 'Zimbabue', 'iso_alpha2' => 'ZW', 'iso_alpha3' => 'ZWE', 'phone_code' => '+263', 'sort_order' => 321],
            ['en_name' => 'Sudan', 'es_name' => 'Sudán', 'iso_alpha2' => 'SD', 'iso_alpha3' => 'SDN', 'phone_code' => '+249', 'sort_order' => 322],
            ['en_name' => 'South Sudan', 'es_name' => 'Sudán del Sur', 'iso_alpha2' => 'SS', 'iso_alpha3' => 'SSD', 'phone_code' => '+211', 'sort_order' => 323],
            ['en_name' => 'Rwanda', 'es_name' => 'Ruanda', 'iso_alpha2' => 'RW', 'iso_alpha3' => 'RWA', 'phone_code' => '+250', 'sort_order' => 324],
            ['en_name' => 'Burundi', 'es_name' => 'Burundi', 'iso_alpha2' => 'BI', 'iso_alpha3' => 'BDI', 'phone_code' => '+257', 'sort_order' => 325],
            ['en_name' => 'Malawi', 'es_name' => 'Malaui', 'iso_alpha2' => 'MW', 'iso_alpha3' => 'MWI', 'phone_code' => '+265', 'sort_order' => 326],
            ['en_name' => 'Mali', 'es_name' => 'Mali', 'iso_alpha2' => 'ML', 'iso_alpha3' => 'MLI', 'phone_code' => '+223', 'sort_order' => 327],
            ['en_name' => 'Burkina Faso', 'es_name' => 'Burkina Faso', 'iso_alpha2' => 'BF', 'iso_alpha3' => 'BFA', 'phone_code' => '+226', 'sort_order' => 328],
            ['en_name' => 'Niger', 'es_name' => 'Níger', 'iso_alpha2' => 'NE', 'iso_alpha3' => 'NER', 'phone_code' => '+227', 'sort_order' => 329],
            ['en_name' => 'Chad', 'es_name' => 'Chad', 'iso_alpha2' => 'TD', 'iso_alpha3' => 'TCD', 'phone_code' => '+235', 'sort_order' => 330],
            ['en_name' => 'Guinea', 'es_name' => 'Guinea', 'iso_alpha2' => 'GN', 'iso_alpha3' => 'GIN', 'phone_code' => '+224', 'sort_order' => 331],
            ['en_name' => 'Benin', 'es_name' => 'Benín', 'iso_alpha2' => 'BJ', 'iso_alpha3' => 'BEN', 'phone_code' => '+229', 'sort_order' => 332],
            ['en_name' => 'Togo', 'es_name' => 'Togo', 'iso_alpha2' => 'TG', 'iso_alpha3' => 'TGO', 'phone_code' => '+228', 'sort_order' => 333],
            ['en_name' => 'Sierra Leone', 'es_name' => 'Sierra Leona', 'iso_alpha2' => 'SL', 'iso_alpha3' => 'SLE', 'phone_code' => '+232', 'sort_order' => 334],
            ['en_name' => 'Liberia', 'es_name' => 'Liberia', 'iso_alpha2' => 'LR', 'iso_alpha3' => 'LBR', 'phone_code' => '+231', 'sort_order' => 335],
            ['en_name' => 'Central African Republic', 'es_name' => 'República Centroafricana', 'iso_alpha2' => 'CF', 'iso_alpha3' => 'CAF', 'phone_code' => '+236', 'sort_order' => 336],
            ['en_name' => 'Eritrea', 'es_name' => 'Eritrea', 'iso_alpha2' => 'ER', 'iso_alpha3' => 'ERI', 'phone_code' => '+291', 'sort_order' => 337],
            ['en_name' => 'Gambia', 'es_name' => 'Gambia', 'iso_alpha2' => 'GM', 'iso_alpha3' => 'GMB', 'phone_code' => '+220', 'sort_order' => 338],
            ['en_name' => 'Botswana', 'es_name' => 'Botsuana', 'iso_alpha2' => 'BW', 'iso_alpha3' => 'BWA', 'phone_code' => '+267', 'sort_order' => 339],
            ['en_name' => 'Namibia', 'es_name' => 'Namibia', 'iso_alpha2' => 'NA', 'iso_alpha3' => 'NAM', 'phone_code' => '+264', 'sort_order' => 340],
            ['en_name' => 'Gabon', 'es_name' => 'Gabón', 'iso_alpha2' => 'GA', 'iso_alpha3' => 'GAB', 'phone_code' => '+241', 'sort_order' => 341],
            ['en_name' => 'Lesotho', 'es_name' => 'Lesoto', 'iso_alpha2' => 'LS', 'iso_alpha3' => 'LSO', 'phone_code' => '+266', 'sort_order' => 342],
            ['en_name' => 'Guinea-Bissau', 'es_name' => 'Guinea-Bisau', 'iso_alpha2' => 'GW', 'iso_alpha3' => 'GNB', 'phone_code' => '+245', 'sort_order' => 343],
            ['en_name' => 'Equatorial Guinea', 'es_name' => 'Guinea Ecuatorial', 'iso_alpha2' => 'GQ', 'iso_alpha3' => 'GNQ', 'phone_code' => '+240', 'sort_order' => 344],
            ['en_name' => 'Mauritius', 'es_name' => 'Mauricio', 'iso_alpha2' => 'MU', 'iso_alpha3' => 'MUS', 'phone_code' => '+230', 'sort_order' => 345],
            ['en_name' => 'Eswatini', 'es_name' => 'Esuatini', 'iso_alpha2' => 'SZ', 'iso_alpha3' => 'SWZ', 'phone_code' => '+268', 'sort_order' => 346],
            ['en_name' => 'Djibouti', 'es_name' => 'Yibuti', 'iso_alpha2' => 'DJ', 'iso_alpha3' => 'DJI', 'phone_code' => '+253', 'sort_order' => 347],
            ['en_name' => 'Comoros', 'es_name' => 'Comoras', 'iso_alpha2' => 'KM', 'iso_alpha3' => 'COM', 'phone_code' => '+269', 'sort_order' => 348],
            ['en_name' => 'Cabo Verde', 'es_name' => 'Cabo Verde', 'iso_alpha2' => 'CV', 'iso_alpha3' => 'CPV', 'phone_code' => '+238', 'sort_order' => 349],
            ['en_name' => 'Sao Tome and Principe', 'es_name' => 'Santo Tomé y Príncipe', 'iso_alpha2' => 'ST', 'iso_alpha3' => 'STP', 'phone_code' => '+239', 'sort_order' => 350],
            ['en_name' => 'Seychelles', 'es_name' => 'Seychelles', 'iso_alpha2' => 'SC', 'iso_alpha3' => 'SYC', 'phone_code' => '+248', 'sort_order' => 351],
            ['en_name' => 'Mauritania', 'es_name' => 'Mauritania', 'iso_alpha2' => 'MR', 'iso_alpha3' => 'MRT', 'phone_code' => '+222', 'sort_order' => 352],
            ['en_name' => 'Somalia', 'es_name' => 'Somalia', 'iso_alpha2' => 'SO', 'iso_alpha3' => 'SOM', 'phone_code' => '+252', 'sort_order' => 353],

            // Oceania
            ['en_name' => 'Australia', 'es_name' => 'Australia', 'iso_alpha2' => 'AU', 'iso_alpha3' => 'AUS', 'phone_code' => '+61', 'sort_order' => 400],
            ['en_name' => 'New Zealand', 'es_name' => 'Nueva Zelanda', 'iso_alpha2' => 'NZ', 'iso_alpha3' => 'NZL', 'phone_code' => '+64', 'sort_order' => 401],
            ['en_name' => 'Papua New Guinea', 'es_name' => 'Papúa Nueva Guinea', 'iso_alpha2' => 'PG', 'iso_alpha3' => 'PNG', 'phone_code' => '+675', 'sort_order' => 402],
            ['en_name' => 'Fiji', 'es_name' => 'Fiyi', 'iso_alpha2' => 'FJ', 'iso_alpha3' => 'FJI', 'phone_code' => '+679', 'sort_order' => 403],
            ['en_name' => 'Solomon Islands', 'es_name' => 'Islas Salomón', 'iso_alpha2' => 'SB', 'iso_alpha3' => 'SLB', 'phone_code' => '+677', 'sort_order' => 404],
            ['en_name' => 'Vanuatu', 'es_name' => 'Vanuatu', 'iso_alpha2' => 'VU', 'iso_alpha3' => 'VUT', 'phone_code' => '+678', 'sort_order' => 405],
            ['en_name' => 'Samoa', 'es_name' => 'Samoa', 'iso_alpha2' => 'WS', 'iso_alpha3' => 'WSM', 'phone_code' => '+685', 'sort_order' => 406],
            ['en_name' => 'Kiribati', 'es_name' => 'Kiribati', 'iso_alpha2' => 'KI', 'iso_alpha3' => 'KIR', 'phone_code' => '+686', 'sort_order' => 407],
            ['en_name' => 'Tonga', 'es_name' => 'Tonga', 'iso_alpha2' => 'TO', 'iso_alpha3' => 'TON', 'phone_code' => '+676', 'sort_order' => 408],
            ['en_name' => 'Micronesia', 'es_name' => 'Micronesia', 'iso_alpha2' => 'FM', 'iso_alpha3' => 'FSM', 'phone_code' => '+691', 'sort_order' => 409],
            ['en_name' => 'Palau', 'es_name' => 'Palaos', 'iso_alpha2' => 'PW', 'iso_alpha3' => 'PLW', 'phone_code' => '+680', 'sort_order' => 410],
            ['en_name' => 'Marshall Islands', 'es_name' => 'Islas Marshall', 'iso_alpha2' => 'MH', 'iso_alpha3' => 'MHL', 'phone_code' => '+692', 'sort_order' => 411],
            ['en_name' => 'Nauru', 'es_name' => 'Nauru', 'iso_alpha2' => 'NR', 'iso_alpha3' => 'NRU', 'phone_code' => '+674', 'sort_order' => 412],
            ['en_name' => 'Tuvalu', 'es_name' => 'Tuvalu', 'iso_alpha2' => 'TV', 'iso_alpha3' => 'TUV', 'phone_code' => '+688', 'sort_order' => 413],

            // Territories and dependencies
            ['en_name' => 'Greenland', 'es_name' => 'Groenlandia', 'iso_alpha2' => 'GL', 'iso_alpha3' => 'GRL', 'phone_code' => '+299', 'sort_order' => 500],
            ['en_name' => 'Faroe Islands', 'es_name' => 'Islas Feroe', 'iso_alpha2' => 'FO', 'iso_alpha3' => 'FRO', 'phone_code' => '+298', 'sort_order' => 501],
            ['en_name' => 'Gibraltar', 'es_name' => 'Gibraltar', 'iso_alpha2' => 'GI', 'iso_alpha3' => 'GIB', 'phone_code' => '+350', 'sort_order' => 502],
            ['en_name' => 'Bermuda', 'es_name' => 'Bermudas', 'iso_alpha2' => 'BM', 'iso_alpha3' => 'BMU', 'phone_code' => '+1-441', 'sort_order' => 503],
            ['en_name' => 'Cayman Islands', 'es_name' => 'Islas Caimán', 'iso_alpha2' => 'KY', 'iso_alpha3' => 'CYM', 'phone_code' => '+1-345', 'sort_order' => 504],
            ['en_name' => 'British Virgin Islands', 'es_name' => 'Islas Vírgenes Británicas', 'iso_alpha2' => 'VG', 'iso_alpha3' => 'VGB', 'phone_code' => '+1-284', 'sort_order' => 505],
            ['en_name' => 'U.S. Virgin Islands', 'es_name' => 'Islas Vírgenes de EE. UU.', 'iso_alpha2' => 'VI', 'iso_alpha3' => 'VIR', 'phone_code' => '+1-340', 'sort_order' => 506],
            ['en_name' => 'Turks and Caicos Islands', 'es_name' => 'Islas Turcas y Caicos', 'iso_alpha2' => 'TC', 'iso_alpha3' => 'TCA', 'phone_code' => '+1-649', 'sort_order' => 507],
            ['en_name' => 'Aruba', 'es_name' => 'Aruba', 'iso_alpha2' => 'AW', 'iso_alpha3' => 'ABW', 'phone_code' => '+297', 'sort_order' => 508],
            ['en_name' => 'Curacao', 'es_name' => 'Curazao', 'iso_alpha2' => 'CW', 'iso_alpha3' => 'CUW', 'phone_code' => '+599', 'sort_order' => 509],
            ['en_name' => 'Sint Maarten', 'es_name' => 'San Martín', 'iso_alpha2' => 'SX', 'iso_alpha3' => 'SXM', 'phone_code' => '+1-721', 'sort_order' => 510],
            ['en_name' => 'Anguilla', 'es_name' => 'Anguila', 'iso_alpha2' => 'AI', 'iso_alpha3' => 'AIA', 'phone_code' => '+1-264', 'sort_order' => 511],
            ['en_name' => 'Montserrat', 'es_name' => 'Montserrat', 'iso_alpha2' => 'MS', 'iso_alpha3' => 'MSR', 'phone_code' => '+1-664', 'sort_order' => 512],
            ['en_name' => 'Guadeloupe', 'es_name' => 'Guadalupe', 'iso_alpha2' => 'GP', 'iso_alpha3' => 'GLP', 'phone_code' => '+590', 'sort_order' => 513],
            ['en_name' => 'Martinique', 'es_name' => 'Martinica', 'iso_alpha2' => 'MQ', 'iso_alpha3' => 'MTQ', 'phone_code' => '+596', 'sort_order' => 514],
            ['en_name' => 'French Guiana', 'es_name' => 'Guayana Francesa', 'iso_alpha2' => 'GF', 'iso_alpha3' => 'GUF', 'phone_code' => '+594', 'sort_order' => 515],
            ['en_name' => 'Saint Barthelemy', 'es_name' => 'San Bartolomé', 'iso_alpha2' => 'BL', 'iso_alpha3' => 'BLM', 'phone_code' => '+590', 'sort_order' => 516],
            ['en_name' => 'Saint Martin', 'es_name' => 'San Martín (Francia)', 'iso_alpha2' => 'MF', 'iso_alpha3' => 'MAF', 'phone_code' => '+590', 'sort_order' => 517],
            ['en_name' => 'Saint Pierre and Miquelon', 'es_name' => 'San Pedro y Miquelón', 'iso_alpha2' => 'PM', 'iso_alpha3' => 'SPM', 'phone_code' => '+508', 'sort_order' => 518],
            ['en_name' => 'Reunion', 'es_name' => 'Reunión', 'iso_alpha2' => 'RE', 'iso_alpha3' => 'REU', 'phone_code' => '+262', 'sort_order' => 519],
            ['en_name' => 'Mayotte', 'es_name' => 'Mayotte', 'iso_alpha2' => 'YT', 'iso_alpha3' => 'MYT', 'phone_code' => '+262', 'sort_order' => 520],
            ['en_name' => 'New Caledonia', 'es_name' => 'Nueva Caledonia', 'iso_alpha2' => 'NC', 'iso_alpha3' => 'NCL', 'phone_code' => '+687', 'sort_order' => 521],
            ['en_name' => 'French Polynesia', 'es_name' => 'Polinesia Francesa', 'iso_alpha2' => 'PF', 'iso_alpha3' => 'PYF', 'phone_code' => '+689', 'sort_order' => 522],
            ['en_name' => 'Wallis and Futuna', 'es_name' => 'Wallis y Futuna', 'iso_alpha2' => 'WF', 'iso_alpha3' => 'WLF', 'phone_code' => '+681', 'sort_order' => 523],
            ['en_name' => 'American Samoa', 'es_name' => 'Samoa Americana', 'iso_alpha2' => 'AS', 'iso_alpha3' => 'ASM', 'phone_code' => '+1-684', 'sort_order' => 524],
            ['en_name' => 'Guam', 'es_name' => 'Guam', 'iso_alpha2' => 'GU', 'iso_alpha3' => 'GUM', 'phone_code' => '+1-671', 'sort_order' => 525],
            ['en_name' => 'Northern Mariana Islands', 'es_name' => 'Islas Marianas del Norte', 'iso_alpha2' => 'MP', 'iso_alpha3' => 'MNP', 'phone_code' => '+1-670', 'sort_order' => 526],
            ['en_name' => 'Cook Islands', 'es_name' => 'Islas Cook', 'iso_alpha2' => 'CK', 'iso_alpha3' => 'COK', 'phone_code' => '+682', 'sort_order' => 527],
            ['en_name' => 'Niue', 'es_name' => 'Niue', 'iso_alpha2' => 'NU', 'iso_alpha3' => 'NIU', 'phone_code' => '+683', 'sort_order' => 528],
            ['en_name' => 'Tokelau', 'es_name' => 'Tokelau', 'iso_alpha2' => 'TK', 'iso_alpha3' => 'TKL', 'phone_code' => '+690', 'sort_order' => 529],
            ['en_name' => 'Norfolk Island', 'es_name' => 'Isla Norfolk', 'iso_alpha2' => 'NF', 'iso_alpha3' => 'NFK', 'phone_code' => '+672', 'sort_order' => 530],
            ['en_name' => 'Christmas Island', 'es_name' => 'Isla de Navidad', 'iso_alpha2' => 'CX', 'iso_alpha3' => 'CXR', 'phone_code' => '+61', 'sort_order' => 531],
            ['en_name' => 'Cocos (Keeling) Islands', 'es_name' => 'Islas Cocos', 'iso_alpha2' => 'CC', 'iso_alpha3' => 'CCK', 'phone_code' => '+61', 'sort_order' => 532],
            ['en_name' => 'Isle of Man', 'es_name' => 'Isla de Man', 'iso_alpha2' => 'IM', 'iso_alpha3' => 'IMN', 'phone_code' => '+44', 'sort_order' => 533],
            ['en_name' => 'Jersey', 'es_name' => 'Jersey', 'iso_alpha2' => 'JE', 'iso_alpha3' => 'JEY', 'phone_code' => '+44', 'sort_order' => 534],
            ['en_name' => 'Guernsey', 'es_name' => 'Guernsey', 'iso_alpha2' => 'GG', 'iso_alpha3' => 'GGY', 'phone_code' => '+44', 'sort_order' => 535],
            ['en_name' => 'Falkland Islands', 'es_name' => 'Islas Malvinas', 'iso_alpha2' => 'FK', 'iso_alpha3' => 'FLK', 'phone_code' => '+500', 'sort_order' => 536],
            ['en_name' => 'South Georgia and the South Sandwich Islands', 'es_name' => 'Georgia del Sur e Islas Sandwich del Sur', 'iso_alpha2' => 'GS', 'iso_alpha3' => 'SGS', 'phone_code' => '+500', 'sort_order' => 537],
            ['en_name' => 'Pitcairn Islands', 'es_name' => 'Islas Pitcairn', 'iso_alpha2' => 'PN', 'iso_alpha3' => 'PCN', 'phone_code' => '+64', 'sort_order' => 538],
            ['en_name' => 'Saint Helena', 'es_name' => 'Santa Elena', 'iso_alpha2' => 'SH', 'iso_alpha3' => 'SHN', 'phone_code' => '+290', 'sort_order' => 539],
            ['en_name' => 'Svalbard and Jan Mayen', 'es_name' => 'Svalbard y Jan Mayen', 'iso_alpha2' => 'SJ', 'iso_alpha3' => 'SJM', 'phone_code' => '+47', 'sort_order' => 540],
            ['en_name' => 'Aland Islands', 'es_name' => 'Islas Aland', 'iso_alpha2' => 'AX', 'iso_alpha3' => 'ALA', 'phone_code' => '+358', 'sort_order' => 541],
            ['en_name' => 'Bonaire, Sint Eustatius and Saba', 'es_name' => 'Bonaire, San Eustaquio y Saba', 'iso_alpha2' => 'BQ', 'iso_alpha3' => 'BES', 'phone_code' => '+599', 'sort_order' => 542],
            ['en_name' => 'Western Sahara', 'es_name' => 'Sahara Occidental', 'iso_alpha2' => 'EH', 'iso_alpha3' => 'ESH', 'phone_code' => '+212', 'sort_order' => 543],
        ];
    }
}
