<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['iso' => 'AF', 'phone_code' => '+93', 'en_name' => 'Afghanistan', 'es_name' => 'Afganistán'],
            ['iso' => 'AX', 'phone_code' => '+358-18', 'en_name' => 'Åland Islands', 'es_name' => 'Islas Åland'],
            ['iso' => 'AL', 'phone_code' => '+355', 'en_name' => 'Albania', 'es_name' => 'Albania'],
            ['iso' => 'DZ', 'phone_code' => '+213', 'en_name' => 'Algeria', 'es_name' => 'Argelia'],
            ['iso' => 'AS', 'phone_code' => '+1-684', 'en_name' => 'American Samoa', 'es_name' => 'Samoa Americana'],
            ['iso' => 'AD', 'phone_code' => '+376', 'en_name' => 'Andorra', 'es_name' => 'Andorra'],
            ['iso' => 'AO', 'phone_code' => '+244', 'en_name' => 'Angola', 'es_name' => 'Angola'],
            ['iso' => 'AI', 'phone_code' => '+1-264', 'en_name' => 'Anguilla', 'es_name' => 'Anguila'],
            ['iso' => 'AQ', 'phone_code' => '+672', 'en_name' => 'Antarctica', 'es_name' => 'Antártida'],
            ['iso' => 'AG', 'phone_code' => '+1-268', 'en_name' => 'Antigua and Barbuda', 'es_name' => 'Antigua y Barbuda'],
            ['iso' => 'AR', 'phone_code' => '+54', 'en_name' => 'Argentina', 'es_name' => 'Argentina'],
            ['iso' => 'AM', 'phone_code' => '+374', 'en_name' => 'Armenia', 'es_name' => 'Armenia'],
            ['iso' => 'AW', 'phone_code' => '+297', 'en_name' => 'Aruba', 'es_name' => 'Aruba'],
            ['iso' => 'AU', 'phone_code' => '+61', 'en_name' => 'Australia', 'es_name' => 'Australia'],
            ['iso' => 'AT', 'phone_code' => '+43', 'en_name' => 'Austria', 'es_name' => 'Austria'],
            ['iso' => 'AZ', 'phone_code' => '+994', 'en_name' => 'Azerbaijan', 'es_name' => 'Azerbaiyán'],
            ['iso' => 'BS', 'phone_code' => '+1-242', 'en_name' => 'Bahamas', 'es_name' => 'Bahamas'],
            ['iso' => 'BH', 'phone_code' => '+973', 'en_name' => 'Bahrain', 'es_name' => 'Baréin'],
            ['iso' => 'BD', 'phone_code' => '+880', 'en_name' => 'Bangladesh', 'es_name' => 'Bangladés'],
            ['iso' => 'BB', 'phone_code' => '+1-246', 'en_name' => 'Barbados', 'es_name' => 'Barbados'],
            ['iso' => 'BY', 'phone_code' => '+375', 'en_name' => 'Belarus', 'es_name' => 'Bielorrusia'],
            ['iso' => 'BE', 'phone_code' => '+32', 'en_name' => 'Belgium', 'es_name' => 'Bélgica'],
            ['iso' => 'BZ', 'phone_code' => '+501', 'en_name' => 'Belize', 'es_name' => 'Belice'],
            ['iso' => 'BJ', 'phone_code' => '+229', 'en_name' => 'Benin', 'es_name' => 'Benín'],
            ['iso' => 'BM', 'phone_code' => '+1-441', 'en_name' => 'Bermuda', 'es_name' => 'Bermudas'],
            ['iso' => 'BT', 'phone_code' => '+975', 'en_name' => 'Bhutan', 'es_name' => 'Bután'],
            ['iso' => 'BO', 'phone_code' => '+591', 'en_name' => 'Bolivia', 'es_name' => 'Bolivia'],
            ['iso' => 'BQ', 'phone_code' => '+599', 'en_name' => 'Bonaire, Sint Eustatius and Saba', 'es_name' => 'Bonaire, San Eustaquio y Saba'],
            ['iso' => 'BA', 'phone_code' => '+387', 'en_name' => 'Bosnia and Herzegovina', 'es_name' => 'Bosnia y Herzegovina'],
            ['iso' => 'BW', 'phone_code' => '+267', 'en_name' => 'Botswana', 'es_name' => 'Botsuana'],
            ['iso' => 'BR', 'phone_code' => '+55', 'en_name' => 'Brazil', 'es_name' => 'Brasil'],
            ['iso' => 'IO', 'phone_code' => '+246', 'en_name' => 'British Indian Ocean Territory', 'es_name' => 'Territorio Británico del Océano Índico'],
            ['iso' => 'VG', 'phone_code' => '+1-284', 'en_name' => 'British Virgin Islands', 'es_name' => 'Islas Vírgenes Británicas'],
            ['iso' => 'BN', 'phone_code' => '+673', 'en_name' => 'Brunei', 'es_name' => 'Brunéi'],
            ['iso' => 'BG', 'phone_code' => '+359', 'en_name' => 'Bulgaria', 'es_name' => 'Bulgaria'],
            ['iso' => 'BF', 'phone_code' => '+226', 'en_name' => 'Burkina Faso', 'es_name' => 'Burkina Faso'],
            ['iso' => 'BI', 'phone_code' => '+257', 'en_name' => 'Burundi', 'es_name' => 'Burundi'],
            ['iso' => 'KH', 'phone_code' => '+855', 'en_name' => 'Cambodia', 'es_name' => 'Camboya'],
            ['iso' => 'CM', 'phone_code' => '+237', 'en_name' => 'Cameroon', 'es_name' => 'Camerún'],
            ['iso' => 'CA', 'phone_code' => '+1', 'en_name' => 'Canada', 'es_name' => 'Canadá'],
            ['iso' => 'CV', 'phone_code' => '+238', 'en_name' => 'Cape Verde', 'es_name' => 'Cabo Verde'],
            ['iso' => 'KY', 'phone_code' => '+1-345', 'en_name' => 'Cayman Islands', 'es_name' => 'Islas Caimán'],
            ['iso' => 'CF', 'phone_code' => '+236', 'en_name' => 'Central African Republic', 'es_name' => 'República Centroafricana'],
            ['iso' => 'TD', 'phone_code' => '+235', 'en_name' => 'Chad', 'es_name' => 'Chad'],
            ['iso' => 'CL', 'phone_code' => '+56', 'en_name' => 'Chile', 'es_name' => 'Chile'],
            ['iso' => 'CN', 'phone_code' => '+86', 'en_name' => 'China', 'es_name' => 'China'],
            ['iso' => 'CX', 'phone_code' => '+61', 'en_name' => 'Christmas Island', 'es_name' => 'Isla de Navidad'],
            ['iso' => 'CC', 'phone_code' => '+61', 'en_name' => 'Cocos (Keeling) Islands', 'es_name' => 'Islas Cocos (Keeling)'],
            ['iso' => 'CO', 'phone_code' => '+57', 'en_name' => 'Colombia', 'es_name' => 'Colombia'],
            ['iso' => 'KM', 'phone_code' => '+269', 'en_name' => 'Comoros', 'es_name' => 'Comoras'],
            ['iso' => 'CG', 'phone_code' => '+242', 'en_name' => 'Republic of the Congo', 'es_name' => 'República del Congo'],
            ['iso' => 'CD', 'phone_code' => '+243', 'en_name' => 'Democratic Republic of the Congo', 'es_name' => 'República Democrática del Congo'],
            ['iso' => 'CK', 'phone_code' => '+682', 'en_name' => 'Cook Islands', 'es_name' => 'Islas Cook'],
            ['iso' => 'CR', 'phone_code' => '+506', 'en_name' => 'Costa Rica', 'es_name' => 'Costa Rica'],
            ['iso' => 'CI', 'phone_code' => '+225', 'en_name' => 'Ivory Coast', 'es_name' => 'Costa de Marfil'],
            ['iso' => 'HR', 'phone_code' => '+385', 'en_name' => 'Croatia', 'es_name' => 'Croacia'],
            ['iso' => 'CU', 'phone_code' => '+53', 'en_name' => 'Cuba', 'es_name' => 'Cuba'],
            ['iso' => 'CW', 'phone_code' => '+599', 'en_name' => 'Curacao', 'es_name' => 'Curazao'],
            ['iso' => 'CY', 'phone_code' => '+357', 'en_name' => 'Cyprus', 'es_name' => 'Chipre'],
            ['iso' => 'CZ', 'phone_code' => '+420', 'en_name' => 'Czech Republic', 'es_name' => 'República Checa'],
            ['iso' => 'DK', 'phone_code' => '+45', 'en_name' => 'Denmark', 'es_name' => 'Dinamarca'],
            ['iso' => 'DJ', 'phone_code' => '+253', 'en_name' => 'Djibouti', 'es_name' => 'Yibuti'],
            ['iso' => 'DM', 'phone_code' => '+1-767', 'en_name' => 'Dominica', 'es_name' => 'Dominica'],
            ['iso' => 'DO', 'phone_code' => '+1-809, +1-829, +1-849', 'en_name' => 'Dominican Republic', 'es_name' => 'República Dominicana'],
            ['iso' => 'EC', 'phone_code' => '+593', 'en_name' => 'Ecuador', 'es_name' => 'Ecuador'],
            ['iso' => 'EG', 'phone_code' => '+20', 'en_name' => 'Egypt', 'es_name' => 'Egipto'],
            ['iso' => 'SV', 'phone_code' => '+503', 'en_name' => 'El Salvador', 'es_name' => 'El Salvador'],
            ['iso' => 'GQ', 'phone_code' => '+240', 'en_name' => 'Equatorial Guinea', 'es_name' => 'Guinea Ecuatorial'],
            ['iso' => 'ER', 'phone_code' => '+291', 'en_name' => 'Eritrea', 'es_name' => 'Eritrea'],
            ['iso' => 'EE', 'phone_code' => '+372', 'en_name' => 'Estonia', 'es_name' => 'Estonia'],
            ['iso' => 'SZ', 'phone_code' => '+268', 'en_name' => 'Eswatini', 'es_name' => 'Esuatini'],
            ['iso' => 'ET', 'phone_code' => '+251', 'en_name' => 'Ethiopia', 'es_name' => 'Etiopía'],
            ['iso' => 'FK', 'phone_code' => '+500', 'en_name' => 'Falkland Islands', 'es_name' => 'Islas Malvinas'],
            ['iso' => 'FO', 'phone_code' => '+298', 'en_name' => 'Faroe Islands', 'es_name' => 'Islas Feroe'],
            ['iso' => 'FJ', 'phone_code' => '+679', 'en_name' => 'Fiji', 'es_name' => 'Fiyi'],
            ['iso' => 'FI', 'phone_code' => '+358', 'en_name' => 'Finland', 'es_name' => 'Finlandia'],
            ['iso' => 'FR', 'phone_code' => '+33', 'en_name' => 'France', 'es_name' => 'Francia'],
            ['iso' => 'GF', 'phone_code' => '+594', 'en_name' => 'French Guiana', 'es_name' => 'Guayana Francesa'],
            ['iso' => 'PF', 'phone_code' => '+689', 'en_name' => 'French Polynesia', 'es_name' => 'Polinesia Francesa'],
            ['iso' => 'GA', 'phone_code' => '+241', 'en_name' => 'Gabon', 'es_name' => 'Gabón'],
            ['iso' => 'GM', 'phone_code' => '+220', 'en_name' => 'Gambia', 'es_name' => 'Gambia'],
            ['iso' => 'GE', 'phone_code' => '+995', 'en_name' => 'Georgia', 'es_name' => 'Georgia'],
            ['iso' => 'DE', 'phone_code' => '+49', 'en_name' => 'Germany', 'es_name' => 'Alemania'],
            ['iso' => 'GH', 'phone_code' => '+233', 'en_name' => 'Ghana', 'es_name' => 'Ghana'],
            ['iso' => 'GI', 'phone_code' => '+350', 'en_name' => 'Gibraltar', 'es_name' => 'Gibraltar'],
            ['iso' => 'GR', 'phone_code' => '+30', 'en_name' => 'Greece', 'es_name' => 'Grecia'],
            ['iso' => 'GL', 'phone_code' => '+299', 'en_name' => 'Greenland', 'es_name' => 'Groenlandia'],
            ['iso' => 'GD', 'phone_code' => '+1-473', 'en_name' => 'Grenada', 'es_name' => 'Granada'],
            ['iso' => 'GP', 'phone_code' => '+590', 'en_name' => 'Guadeloupe', 'es_name' => 'Guadalupe'],
            ['iso' => 'GU', 'phone_code' => '+1-671', 'en_name' => 'Guam', 'es_name' => 'Guam'],
            ['iso' => 'GT', 'phone_code' => '+502', 'en_name' => 'Guatemala', 'es_name' => 'Guatemala'],
            ['iso' => 'GG', 'phone_code' => '+44-1481', 'en_name' => 'Guernsey', 'es_name' => 'Guernsey'],
            ['iso' => 'GN', 'phone_code' => '+224', 'en_name' => 'Guinea', 'es_name' => 'Guinea'],
            ['iso' => 'GW', 'phone_code' => '+245', 'en_name' => 'Guinea-Bissau', 'es_name' => 'Guinea-Bisáu'],
            ['iso' => 'GY', 'phone_code' => '+592', 'en_name' => 'Guyana', 'es_name' => 'Guyana'],
            ['iso' => 'HT', 'phone_code' => '+509', 'en_name' => 'Haiti', 'es_name' => 'Haití'],
            ['iso' => 'HN', 'phone_code' => '+504', 'en_name' => 'Honduras', 'es_name' => 'Honduras'],
            ['iso' => 'HK', 'phone_code' => '+852', 'en_name' => 'Hong Kong', 'es_name' => 'Hong Kong'],
            ['iso' => 'HU', 'phone_code' => '+36', 'en_name' => 'Hungary', 'es_name' => 'Hungría'],
            ['iso' => 'IS', 'phone_code' => '+354', 'en_name' => 'Iceland', 'es_name' => 'Islandia'],
            ['iso' => 'IN', 'phone_code' => '+91', 'en_name' => 'India', 'es_name' => 'India'],
            ['iso' => 'ID', 'phone_code' => '+62', 'en_name' => 'Indonesia', 'es_name' => 'Indonesia'],
            ['iso' => 'IR', 'phone_code' => '+98', 'en_name' => 'Iran', 'es_name' => 'Irán'],
            ['iso' => 'IQ', 'phone_code' => '+964', 'en_name' => 'Iraq', 'es_name' => 'Irak'],
            ['iso' => 'IE', 'phone_code' => '+353', 'en_name' => 'Ireland', 'es_name' => 'Irlanda'],
            ['iso' => 'IM', 'phone_code' => '+44-1624', 'en_name' => 'Isle of Man', 'es_name' => 'Isla de Man'],
            ['iso' => 'IL', 'phone_code' => '+972', 'en_name' => 'Israel', 'es_name' => 'Israel'],
            ['iso' => 'IT', 'phone_code' => '+39', 'en_name' => 'Italy', 'es_name' => 'Italia'],
            ['iso' => 'JM', 'phone_code' => '+1-876', 'en_name' => 'Jamaica', 'es_name' => 'Jamaica'],
            ['iso' => 'JP', 'phone_code' => '+81', 'en_name' => 'Japan', 'es_name' => 'Japón'],
            ['iso' => 'JE', 'phone_code' => '+44-1534', 'en_name' => 'Jersey', 'es_name' => 'Jersey'],
            ['iso' => 'JO', 'phone_code' => '+962', 'en_name' => 'Jordan', 'es_name' => 'Jordania'],
            ['iso' => 'KZ', 'phone_code' => '+7', 'en_name' => 'Kazakhstan', 'es_name' => 'Kazajistán'],
            ['iso' => 'KE', 'phone_code' => '+254', 'en_name' => 'Kenya', 'es_name' => 'Kenia'],
            ['iso' => 'KI', 'phone_code' => '+686', 'en_name' => 'Kiribati', 'es_name' => 'Kiribati'],
            ['iso' => 'XK', 'phone_code' => '+383', 'en_name' => 'Kosovo', 'es_name' => 'Kosovo'],
            ['iso' => 'KW', 'phone_code' => '+965', 'en_name' => 'Kuwait', 'es_name' => 'Kuwait'],
            ['iso' => 'KG', 'phone_code' => '+996', 'en_name' => 'Kyrgyzstan', 'es_name' => 'Kirguistán'],
            ['iso' => 'LA', 'phone_code' => '+856', 'en_name' => 'Laos', 'es_name' => 'Laos'],
            ['iso' => 'LV', 'phone_code' => '+371', 'en_name' => 'Latvia', 'es_name' => 'Letonia'],
            ['iso' => 'LB', 'phone_code' => '+961', 'en_name' => 'Lebanon', 'es_name' => 'Líbano'],
            ['iso' => 'LS', 'phone_code' => '+266', 'en_name' => 'Lesotho', 'es_name' => 'Lesoto'],
            ['iso' => 'LR', 'phone_code' => '+231', 'en_name' => 'Liberia', 'es_name' => 'Liberia'],
            ['iso' => 'LY', 'phone_code' => '+218', 'en_name' => 'Libya', 'es_name' => 'Libia'],
            ['iso' => 'LI', 'phone_code' => '+423', 'en_name' => 'Liechtenstein', 'es_name' => 'Liechtenstein'],
            ['iso' => 'LT', 'phone_code' => '+370', 'en_name' => 'Lithuania', 'es_name' => 'Lituania'],
            ['iso' => 'LU', 'phone_code' => '+352', 'en_name' => 'Luxembourg', 'es_name' => 'Luxemburgo'],
            ['iso' => 'MO', 'phone_code' => '+853', 'en_name' => 'Macau', 'es_name' => 'Macao'],
            ['iso' => 'MG', 'phone_code' => '+261', 'en_name' => 'Madagascar', 'es_name' => 'Madagascar'],
            ['iso' => 'MW', 'phone_code' => '+265', 'en_name' => 'Malawi', 'es_name' => 'Malaui'],
            ['iso' => 'MY', 'phone_code' => '+60', 'en_name' => 'Malaysia', 'es_name' => 'Malasia'],
            ['iso' => 'MV', 'phone_code' => '+960', 'en_name' => 'Maldives', 'es_name' => 'Maldivas'],
            ['iso' => 'ML', 'phone_code' => '+223', 'en_name' => 'Mali', 'es_name' => 'Malí'],
            ['iso' => 'MT', 'phone_code' => '+356', 'en_name' => 'Malta', 'es_name' => 'Malta'],
            ['iso' => 'MH', 'phone_code' => '+692', 'en_name' => 'Marshall Islands', 'es_name' => 'Islas Marshall'],
            ['iso' => 'MQ', 'phone_code' => '+596', 'en_name' => 'Martinique', 'es_name' => 'Martinica'],
            ['iso' => 'MR', 'phone_code' => '+222', 'en_name' => 'Mauritania', 'es_name' => 'Mauritania'],
            ['iso' => 'MU', 'phone_code' => '+230', 'en_name' => 'Mauritius', 'es_name' => 'Mauricio'],
            ['iso' => 'YT', 'phone_code' => '+262', 'en_name' => 'Mayotte', 'es_name' => 'Mayotte'],
            ['iso' => 'MX', 'phone_code' => '+52', 'en_name' => 'Mexico', 'es_name' => 'México'],
            ['iso' => 'FM', 'phone_code' => '+691', 'en_name' => 'Micronesia', 'es_name' => 'Micronesia'],
            ['iso' => 'MD', 'phone_code' => '+373', 'en_name' => 'Moldova', 'es_name' => 'Moldavia'],
            ['iso' => 'MC', 'phone_code' => '+377', 'en_name' => 'Monaco', 'es_name' => 'Mónaco'],
            ['iso' => 'MN', 'phone_code' => '+976', 'en_name' => 'Mongolia', 'es_name' => 'Mongolia'],
            ['iso' => 'ME', 'phone_code' => '+382', 'en_name' => 'Montenegro', 'es_name' => 'Montenegro'],
            ['iso' => 'MS', 'phone_code' => '+1-664', 'en_name' => 'Montserrat', 'es_name' => 'Montserrat'],
            ['iso' => 'MA', 'phone_code' => '+212', 'en_name' => 'Morocco', 'es_name' => 'Marruecos'],
            ['iso' => 'MZ', 'phone_code' => '+258', 'en_name' => 'Mozambique', 'es_name' => 'Mozambique'],
            ['iso' => 'MM', 'phone_code' => '+95', 'en_name' => 'Myanmar', 'es_name' => 'Myanmar'],
            ['iso' => 'NA', 'phone_code' => '+264', 'en_name' => 'Namibia', 'es_name' => 'Namibia'],
            ['iso' => 'NR', 'phone_code' => '+674', 'en_name' => 'Nauru', 'es_name' => 'Nauru'],
            ['iso' => 'NP', 'phone_code' => '+977', 'en_name' => 'Nepal', 'es_name' => 'Nepal'],
            ['iso' => 'NL', 'phone_code' => '+31', 'en_name' => 'Netherlands', 'es_name' => 'Países Bajos'],
            ['iso' => 'NC', 'phone_code' => '+687', 'en_name' => 'New Caledonia', 'es_name' => 'Nueva Caledonia'],
            ['iso' => 'NZ', 'phone_code' => '+64', 'en_name' => 'New Zealand', 'es_name' => 'Nueva Zelanda'],
            ['iso' => 'NI', 'phone_code' => '+505', 'en_name' => 'Nicaragua', 'es_name' => 'Nicaragua'],
            ['iso' => 'NE', 'phone_code' => '+227', 'en_name' => 'Niger', 'es_name' => 'Níger'],
            ['iso' => 'NG', 'phone_code' => '+234', 'en_name' => 'Nigeria', 'es_name' => 'Nigeria'],
            ['iso' => 'NU', 'phone_code' => '+683', 'en_name' => 'Niue', 'es_name' => 'Niue'],
            ['iso' => 'NF', 'phone_code' => '+672', 'en_name' => 'Norfolk Island', 'es_name' => 'Isla Norfolk'],
            ['iso' => 'KP', 'phone_code' => '+850', 'en_name' => 'North Korea', 'es_name' => 'Corea del Norte'],
            ['iso' => 'MK', 'phone_code' => '+389', 'en_name' => 'North Macedonia', 'es_name' => 'Macedonia del Norte'],
            ['iso' => 'MP', 'phone_code' => '+1-670', 'en_name' => 'Northern Mariana Islands', 'es_name' => 'Islas Marianas del Norte'],
            ['iso' => 'NO', 'phone_code' => '+47', 'en_name' => 'Norway', 'es_name' => 'Noruega'],
            ['iso' => 'OM', 'phone_code' => '+968', 'en_name' => 'Oman', 'es_name' => 'Omán'],
            ['iso' => 'PK', 'phone_code' => '+92', 'en_name' => 'Pakistan', 'es_name' => 'Pakistán'],
            ['iso' => 'PW', 'phone_code' => '+680', 'en_name' => 'Palau', 'es_name' => 'Palaos'],
            ['iso' => 'PS', 'phone_code' => '+970', 'en_name' => 'Palestine', 'es_name' => 'Palestina'],
            ['iso' => 'PA', 'phone_code' => '+507', 'en_name' => 'Panama', 'es_name' => 'Panamá'],
            ['iso' => 'PG', 'phone_code' => '+675', 'en_name' => 'Papua New Guinea', 'es_name' => 'Papúa Nueva Guinea'],
            ['iso' => 'PY', 'phone_code' => '+595', 'en_name' => 'Paraguay', 'es_name' => 'Paraguay'],
            ['iso' => 'PE', 'phone_code' => '+51', 'en_name' => 'Peru', 'es_name' => 'Perú'],
            ['iso' => 'PH', 'phone_code' => '+63', 'en_name' => 'Philippines', 'es_name' => 'Filipinas'],
            ['iso' => 'PN', 'phone_code' => '+64', 'en_name' => 'Pitcairn Islands', 'es_name' => 'Islas Pitcairn'],
            ['iso' => 'PL', 'phone_code' => '+48', 'en_name' => 'Poland', 'es_name' => 'Polonia'],
            ['iso' => 'PT', 'phone_code' => '+351', 'en_name' => 'Portugal', 'es_name' => 'Portugal'],
            ['iso' => 'PR', 'phone_code' => '+1-787, +1-939', 'en_name' => 'Puerto Rico', 'es_name' => 'Puerto Rico'],
            ['iso' => 'QA', 'phone_code' => '+974', 'en_name' => 'Qatar', 'es_name' => 'Catar'],
            ['iso' => 'RE', 'phone_code' => '+262', 'en_name' => 'Reunion', 'es_name' => 'Reunión'],
            ['iso' => 'RO', 'phone_code' => '+40', 'en_name' => 'Romania', 'es_name' => 'Rumania'],
            ['iso' => 'RU', 'phone_code' => '+7', 'en_name' => 'Russia', 'es_name' => 'Rusia'],
            ['iso' => 'RW', 'phone_code' => '+250', 'en_name' => 'Rwanda', 'es_name' => 'Ruanda'],
            ['iso' => 'BL', 'phone_code' => '+590', 'en_name' => 'Saint Barthelemy', 'es_name' => 'San Bartolomé'],
            ['iso' => 'SH', 'phone_code' => '+290', 'en_name' => 'Saint Helena', 'es_name' => 'Santa Elena'],
            ['iso' => 'KN', 'phone_code' => '+1-869', 'en_name' => 'Saint Kitts and Nevis', 'es_name' => 'San Cristóbal y Nieves'],
            ['iso' => 'LC', 'phone_code' => '+1-758', 'en_name' => 'Saint Lucia', 'es_name' => 'Santa Lucía'],
            ['iso' => 'MF', 'phone_code' => '+590', 'en_name' => 'Saint Martin', 'es_name' => 'San Martín (parte francesa)'],
            ['iso' => 'PM', 'phone_code' => '+508', 'en_name' => 'Saint Pierre and Miquelon', 'es_name' => 'San Pedro y Miquelón'],
            ['iso' => 'VC', 'phone_code' => '+1-784', 'en_name' => 'Saint Vincent and the Grenadines', 'es_name' => 'San Vicente y las Granadinas'],
            ['iso' => 'WS', 'phone_code' => '+685', 'en_name' => 'Samoa', 'es_name' => 'Samoa'],
            ['iso' => 'SM', 'phone_code' => '+378', 'en_name' => 'San Marino', 'es_name' => 'San Marino'],
            ['iso' => 'ST', 'phone_code' => '+239', 'en_name' => 'Sao Tome and Principe', 'es_name' => 'Santo Tomé y Príncipe'],
            ['iso' => 'SA', 'phone_code' => '+966', 'en_name' => 'Saudi Arabia', 'es_name' => 'Arabia Saudita'],
            ['iso' => 'SN', 'phone_code' => '+221', 'en_name' => 'Senegal', 'es_name' => 'Senegal'],
            ['iso' => 'RS', 'phone_code' => '+381', 'en_name' => 'Serbia', 'es_name' => 'Serbia'],
            ['iso' => 'SC', 'phone_code' => '+248', 'en_name' => 'Seychelles', 'es_name' => 'Seychelles'],
            ['iso' => 'SL', 'phone_code' => '+232', 'en_name' => 'Sierra Leone', 'es_name' => 'Sierra Leona'],
            ['iso' => 'SG', 'phone_code' => '+65', 'en_name' => 'Singapore', 'es_name' => 'Singapur'],
            ['iso' => 'SX', 'phone_code' => '+1-721', 'en_name' => 'Sint Maarten', 'es_name' => 'San Martín (parte neerlandesa)'],
            ['iso' => 'SK', 'phone_code' => '+421', 'en_name' => 'Slovakia', 'es_name' => 'Eslovaquia'],
            ['iso' => 'SI', 'phone_code' => '+386', 'en_name' => 'Slovenia', 'es_name' => 'Eslovenia'],
            ['iso' => 'SB', 'phone_code' => '+677', 'en_name' => 'Solomon Islands', 'es_name' => 'Islas Salomón'],
            ['iso' => 'SO', 'phone_code' => '+252', 'en_name' => 'Somalia', 'es_name' => 'Somalia'],
            ['iso' => 'ZA', 'phone_code' => '+27', 'en_name' => 'South Africa', 'es_name' => 'Sudáfrica'],
            ['iso' => 'GS', 'phone_code' => '+500', 'en_name' => 'South Georgia and the South Sandwich Islands', 'es_name' => 'Islas Georgias del Sur y Sandwich del Sur'],
            ['iso' => 'KR', 'phone_code' => '+82', 'en_name' => 'South Korea', 'es_name' => 'Corea del Sur'],
            ['iso' => 'SS', 'phone_code' => '+211', 'en_name' => 'South Sudan', 'es_name' => 'Sudán del Sur'],
            ['iso' => 'ES', 'phone_code' => '+34', 'en_name' => 'Spain', 'es_name' => 'España'],
            ['iso' => 'LK', 'phone_code' => '+94', 'en_name' => 'Sri Lanka', 'es_name' => 'Sri Lanka'],
            ['iso' => 'SD', 'phone_code' => '+249', 'en_name' => 'Sudan', 'es_name' => 'Sudán'],
            ['iso' => 'SR', 'phone_code' => '+597', 'en_name' => 'Suriname', 'es_name' => 'Surinam'],
            ['iso' => 'SJ', 'phone_code' => '+47', 'en_name' => 'Svalbard and Jan Mayen', 'es_name' => 'Svalbard y Jan Mayen'],
            ['iso' => 'SE', 'phone_code' => '+46', 'en_name' => 'Sweden', 'es_name' => 'Suecia'],
            ['iso' => 'CH', 'phone_code' => '+41', 'en_name' => 'Switzerland', 'es_name' => 'Suiza'],
            ['iso' => 'SY', 'phone_code' => '+963', 'en_name' => 'Syria', 'es_name' => 'Siria'],
            ['iso' => 'TW', 'phone_code' => '+886', 'en_name' => 'Taiwan', 'es_name' => 'Taiwán'],
            ['iso' => 'TJ', 'phone_code' => '+992', 'en_name' => 'Tajikistan', 'es_name' => 'Tayikistán'],
            ['iso' => 'TZ', 'phone_code' => '+255', 'en_name' => 'Tanzania', 'es_name' => 'Tanzania'],
            ['iso' => 'TH', 'phone_code' => '+66', 'en_name' => 'Thailand', 'es_name' => 'Tailandia'],
            ['iso' => 'TL', 'phone_code' => '+670', 'en_name' => 'East Timor', 'es_name' => 'Timor Oriental'],
            ['iso' => 'TG', 'phone_code' => '+228', 'en_name' => 'Togo', 'es_name' => 'Togo'],
            ['iso' => 'TK', 'phone_code' => '+690', 'en_name' => 'Tokelau', 'es_name' => 'Tokelau'],
            ['iso' => 'TO', 'phone_code' => '+676', 'en_name' => 'Tonga', 'es_name' => 'Tonga'],
            ['iso' => 'TT', 'phone_code' => '+1-868', 'en_name' => 'Trinidad and Tobago', 'es_name' => 'Trinidad y Tobago'],
            ['iso' => 'TN', 'phone_code' => '+216', 'en_name' => 'Tunisia', 'es_name' => 'Túnez'],
            ['iso' => 'TR', 'phone_code' => '+90', 'en_name' => 'Turkey', 'es_name' => 'Turquía'],
            ['iso' => 'TM', 'phone_code' => '+993', 'en_name' => 'Turkmenistan', 'es_name' => 'Turkmenistán'],
            ['iso' => 'TC', 'phone_code' => '+1-649', 'en_name' => 'Turks and Caicos Islands', 'es_name' => 'Islas Turcas y Caicos'],
            ['iso' => 'TV', 'phone_code' => '+688', 'en_name' => 'Tuvalu', 'es_name' => 'Tuvalu'],
            ['iso' => 'UG', 'phone_code' => '+256', 'en_name' => 'Uganda', 'es_name' => 'Uganda'],
            ['iso' => 'UA', 'phone_code' => '+380', 'en_name' => 'Ukraine', 'es_name' => 'Ucrania'],
            ['iso' => 'AE', 'phone_code' => '+971', 'en_name' => 'United Arab Emirates', 'es_name' => 'Emiratos Árabes Unidos'],
            ['iso' => 'GB', 'phone_code' => '+44', 'en_name' => 'United Kingdom', 'es_name' => 'Reino Unido'],
            ['iso' => 'US', 'phone_code' => '+1', 'en_name' => 'United States', 'es_name' => 'Estados Unidos'],
            ['iso' => 'UY', 'phone_code' => '+598', 'en_name' => 'Uruguay', 'es_name' => 'Uruguay'],
            ['iso' => 'VI', 'phone_code' => '+1-340', 'en_name' => 'U.S. Virgin Islands', 'es_name' => 'Islas Vírgenes de los Estados Unidos'],
            ['iso' => 'UZ', 'phone_code' => '+998', 'en_name' => 'Uzbekistan', 'es_name' => 'Uzbekistán'],
            ['iso' => 'VU', 'phone_code' => '+678', 'en_name' => 'Vanuatu', 'es_name' => 'Vanuatu'],
            ['iso' => 'VA', 'phone_code' => '+379', 'en_name' => 'Vatican City', 'es_name' => 'Ciudad del Vaticano'],
            ['iso' => 'VE', 'phone_code' => '+58', 'en_name' => 'Venezuela', 'es_name' => 'Venezuela'],
            ['iso' => 'VN', 'phone_code' => '+84', 'en_name' => 'Vietnam', 'es_name' => 'Vietnam'],
            ['iso' => 'WF', 'phone_code' => '+681', 'en_name' => 'Wallis and Futuna', 'es_name' => 'Wallis y Futuna'],
            ['iso' => 'EH', 'phone_code' => '+212', 'en_name' => 'Western Sahara', 'es_name' => 'Sáhara Occidental'],
            ['iso' => 'YE', 'phone_code' => '+967', 'en_name' => 'Yemen', 'es_name' => 'Yemen'],
            ['iso' => 'ZM', 'phone_code' => '+260', 'en_name' => 'Zambia', 'es_name' => 'Zambia'],
            ['iso' => 'ZW', 'phone_code' => '+263', 'en_name' => 'Zimbabwe', 'es_name' => 'Zimbabue'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso_code' => $country['iso']],
                [
                    'en_name' => $country['en_name'],
                    'es_name' => $country['es_name'],
                    'phone_code' => $country['phone_code']
                ]
            );
        }
    }
}
